ALTER TABLE users
  ADD COLUMN IF NOT EXISTS otp VARCHAR(10) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS otp_expiry DATETIME DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT FALSE;

UPDATE users
SET is_verified = TRUE
WHERE role IN ('admin', 'staff');
